name: "GitHub Action to unlock git-crypt secrets"
description: "Unlock secrets using git-crypt from encoded secret-key"
author: "Arnaud Rinquin"
branding:
  icon: "unlock"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
